workflows:
  ios-workflow:
    name: iOS workflow
    integrations:
      app_store_connect: build
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: nu.24-timmars
#      groups:
      # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
#        - app_store_credentials # <-- (APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
          # APP_STORE_CONNECT_ISSUER_ID <-- Put your App Store Connect Issuer Id here
          # APP_STORE_CONNECT_KEY_IDENTIFIER <-- Put your App Store Connect Key Identifier here
          # APP_STORE_CONNECT_PRIVATE_KEY <-- Put your App Store Connect Private Key here
#        - certificate_credentials # <-- (CERTIFICATE_PRIVATE_KEY - Put your Certificate Private Key here)
      vars:
        XCODE_WORKSPACE: "24h-app/platforms/ios/SXK 24-timmars.xcworkspace" # <-- Put the name of your workspace here.
        XCODE_SCHEME: "SXK 24-timmars" # <-- Put the name of your scheme here.
        BUNDLE_ID: "nu.24-timmars" # <-- Put your Bundle Id here.
        APP_STORE_APPLE_ID: 1273150842 # <-- Put your Apple App ID here. This can be found in App Store Connect > Your App > General > App Information > Apple ID.
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      node: v16.11.1
      npm: 6
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - $CM_BUILD_DIR/tiles
    scripts:
      - name: Fetch map
        script: |
          make tiles
      - name: Build app
        script: |
          make 24h-app
      - name: Setup iOS
        script: |
          cd 24h-app
          cordova platform remove ios --nosave
          cordova platform add ios --confirm --no-interactive --noresources --save
#      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
#        script: |
#          keychain initialize
#      - name: Fetch signing files
#        script: |
#          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
#      - name: Add certificates to keychain
#        script: |
#          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          cd 24h-app
          package_type=$(defaults read ~/export_options.plist method)
          identity=$(defaults read ~/export_options.plist signingCertificate)
          team=$(defaults read ~/export_options.plist teamID)
          profile=$(find '/Users/builder/Library/MobileDevice/Provisioning Profiles' -name "*.mobileprovision")
          profile_uuid=$(grep UUID -A1 -a "$profile" | grep -io "[-A-F0-9]\{36\}")

          cat <<EOF > build.json
              {
                "ios": {
                  "release": {
                    "codeSignIdentity": "$identity",
                    "developmentTeam": "$team",
                    "packageType": "$package_type",
                    "provisioningProfile": "$profile_uuid"
                  }
                }
              }
          EOF
          cordova build ios --release --device --buildConfig='build.json'
    artifacts:
      - /Users/builder/clone/platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - mbj4668@gmail.com
        notify:
          success: true     # To not receive a notification when a build succeeds
          failure: true    # To not receive a notification when a build fails
      app_store_connect:
        auth: integration
        # api_key: $APP_STORE_CONNECT_PRIVATE_KEY         # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
        # key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER       # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
        # issuer_id: $APP_STORE_CONNECT_ISSUER_ID         # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false                     # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight beta review. Required for distributing to beta groups. Note: This action is performed during post-processing.
        # beta_groups:                                  # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
        #      - group name 1
        #      - group name 2
